title: "PlayerGloves"
name: "luma44"

repository: "halfdane/luma_poc"

defaults:
  # _posts
  - scope:
      path: ""
      type: posts
    values:
      layout: single
      show_date: true
      read_time: true
      author_profile: true
      header:
        show_overlay_excerpt: false
  # _pages
  - scope:
      path: ""
      type: pages
    values:
      layout: single
      author_profile: true


author:
  name     : "luma44"
  avatar   : "https://www.gstop-content.com/ipfs/QmWst28JaLn5xhptaQryw8XeYP2Z8DVifKPYTVs4H7N3Ve?img-width=200&image-format=WebP"
  bio      : "Jack of all trades - but born to create!  Excited to be bringing my genesis NFT collection to this amazing marketplace.  I have some big projects in store... and hodling one of my NFTs might be the *key* to being involved"
  location : "US"
  links:
    - label: "Reddit"
      icon: "fab fa-fw fa-reddit"
      url: "https://www.reddit.com/user/luma44"
    - label: "0x5bead37adcae9bae8a3d1db2ced942fde2c3c971"
      icon: "fab fa-fw fa-ethereum"
      url: "https://etherscan.io/address/0x5bead37adcae9bae8a3d1db2ced942fde2c3c971"
    - label: "Gamestop NFT Marketplace"
      url: "https://nft.gamestop.com/user/luma44"


footer:
  links:
    - label: "Gamestop NFT Marketplace"
      url: "https://nft.gamestop.com/user/luma44"

minimal_mistakes_skin: "dirt"
remote_theme: "mmistakes/minimal-mistakes@4.24.0"

paginate: 8 # amount of posts to show
paginate_path: /blog/page:num/


plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-gist
  - jekyll-feed
  - jekyll-include-cache

include:
  - .htaccess
  - _pages
exclude:
  - "*.sublime-project"
  - "*.sublime-workspace"
  - vendor
  - .asset-cache
  - .idea
  - .bundle
  - .jekyll-assets-cache
  - .sass-cache
  - assets/js/plugins
  - assets/js/_main.js
  - assets/js/vendor
  - Capfile
  - CHANGELOG
  - config
  - Gemfile
  - Gruntfile.js
  - gulpfile.js
  - LICENSE
  - log
  - node_modules
  - package.json
  - package-lock.json
  - Rakefile
  - README
  - tmp
  - /docs # ignore Minimal Mistakes /docs
  - /test # ignore Minimal Mistakes /test
keep_files:
  - .git
  - .svn
encoding: "utf-8"
markdown_ext: "markdown,mkdown,mkdn,mkd,md"

